"""Rename hash_password to hashed_password in User model

Revision ID: c70153994d8a
Revises: 32dc2892addf
Create Date: 2025-05-28 19:32:44.836548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c70153994d8a'
down_revision: Union[str, None] = '32dc2892addf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=128), nullable=False))
        batch_op.drop_column('hash_password')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_password', mysql.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
