"""Initial migration

Revision ID: cb99373eb317
Revises: 
Create Date: 2025-05-28 18:08:20.894003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb99373eb317'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hash_password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pegawai'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kategori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kategori_id'), ['id'], unique=False)

    op.create_table('log_autentikasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_autentikasi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_autentikasi_id'), ['id'], unique=False)

    op.create_table('tugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('prioritas', sa.Enum('low', 'medium', 'high'), nullable=False),
    sa.Column('status', sa.Enum('to_do', 'in_progress', 'done', 'archived'), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=True),
    sa.Column('tanggal_selesai', sa.Date(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tugas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tugas_id'), ['id'], unique=False)

    op.create_table('komentar_tugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tugas_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('komentar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tugas_id'], ['tugas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('komentar_tugas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_komentar_tugas_id'), ['id'], unique=False)

    op.create_table('lampiran_tugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tugas_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tugas_id'], ['tugas.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lampiran_tugas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lampiran_tugas_id'), ['id'], unique=False)

    op.create_table('penugasan_tugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tugas_id', sa.Integer(), nullable=False),
    sa.Column('pegawai_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pegawai_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tugas_id'], ['tugas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penugasan_tugas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penugasan_tugas_id'), ['id'], unique=False)

    op.create_table('riwayat_status_tugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tugas_id', sa.Integer(), nullable=False),
    sa.Column('status_lama', sa.Enum('to_do', 'in_progress', 'done', 'archived'), nullable=True),
    sa.Column('status_baru', sa.Enum('to_do', 'in_progress', 'done', 'archived'), nullable=True),
    sa.Column('diubah_oleh', sa.Integer(), nullable=False),
    sa.Column('waktu_ubah', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diubah_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tugas_id'], ['tugas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riwayat_status_tugas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riwayat_status_tugas_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_status_tugas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riwayat_status_tugas_id'))

    op.drop_table('riwayat_status_tugas')
    with op.batch_alter_table('penugasan_tugas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penugasan_tugas_id'))

    op.drop_table('penugasan_tugas')
    with op.batch_alter_table('lampiran_tugas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lampiran_tugas_id'))

    op.drop_table('lampiran_tugas')
    with op.batch_alter_table('komentar_tugas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_komentar_tugas_id'))

    op.drop_table('komentar_tugas')
    with op.batch_alter_table('tugas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tugas_id'))

    op.drop_table('tugas')
    with op.batch_alter_table('log_autentikasi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_autentikasi_id'))

    op.drop_table('log_autentikasi')
    with op.batch_alter_table('kategori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kategori_id'))

    op.drop_table('kategori')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
